<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="PSM" nsURI="http://localhost/mdd/PSM.ecore" nsPrefix="PSM">
  <eClassifiers xsi:type="ecore:EClass" name="ArtifactElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ParentProjectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ArtifactFileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GeneratingLinesOfCode"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RootPSM">
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" lowerBound="1"
        eType="#//DistributedApplicationProject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DistributedApplicationProject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ApplicationName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ProjectPackageURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containers" lowerBound="1"
        upperBound="-1" eType="#//DockerContainerDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="application_project" lowerBound="1"
        eType="#//ApplicationProject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DockerContainerDefinition" eSuperTypes="#//ArtifactElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ContainerName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GeneratesLogs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ImageField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BuildField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//DockerContainerLink" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" lowerBound="1" upperBound="-1"
        eType="#//DockerContainerPort" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DockerContainerLink" eSuperTypes="#//ArtifactElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DependencyOrder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LinksDependsOnField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DockerContainerPort" eSuperTypes="#//ArtifactElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ExposesPortsField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationProject" eSuperTypes="#//ArtifactElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ProjectArtifactId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" lowerBound="1"
        upperBound="-1" eType="#//MicroserviceProject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MicroserviceProject" eSuperTypes="#//ArtifactElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ProjectArtifactId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="libraries" lowerBound="1"
        upperBound="-1" eType="#//DependencyLibrary" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" lowerBound="1"
        upperBound="-1" eType="#//ConfigurationProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependencyLibrary" eSuperTypes="#//ArtifactElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LibraryGroupName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LibraryName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LibraryScope" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaSpringWebApplicationProject" eSuperTypes="#//MicroserviceProject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="layers" lowerBound="2"
        upperBound="-1" eType="#//SpringWebApplicationLayer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaSpringWebFluxApplicationProject"
      eSuperTypes="#//JavaSpringWebApplicationProject"/>
  <eClassifiers xsi:type="ecore:EClass" name="JavaSpringMVCApplicationProject" eSuperTypes="#//JavaSpringWebApplicationProject"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationProperty" eSuperTypes="#//ArtifactElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FullyQualifiedPropertyName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PropertyValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ConfigurationProfile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="global"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpringWebApplicationLayer" eSuperTypes="#//ArtifactElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LayerName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="#//JavaUserDefinedType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpringBootApplicationLayer" eSuperTypes="#//SpringWebApplicationLayer"/>
  <eClassifiers xsi:type="ecore:EClass" name="SpringControllerLayer" eSuperTypes="#//SpringWebApplicationLayer"/>
  <eClassifiers xsi:type="ecore:EClass" name="SpringServiceLayer" eSuperTypes="#//SpringWebApplicationLayer"/>
  <eClassifiers xsi:type="ecore:EClass" name="SpringConfigurationLayer" eSuperTypes="#//SpringWebApplicationLayer"/>
  <eClassifiers xsi:type="ecore:EClass" name="SpringFeignClientLayer" eSuperTypes="#//SpringWebApplicationLayer"/>
  <eClassifiers xsi:type="ecore:EClass" name="SpringComponentLayer" eSuperTypes="#//SpringWebApplicationLayer"/>
  <eClassifiers xsi:type="ecore:EClass" name="SpringRepositoryLayer" eSuperTypes="#//SpringWebApplicationLayer"/>
  <eClassifiers xsi:type="ecore:EClass" name="SpringDomainLayer" eSuperTypes="#//SpringWebApplicationLayer"/>
  <eClassifiers xsi:type="ecore:EClass" name="SpringModelPojoLayer" eSuperTypes="#//SpringWebApplicationLayer"/>
  <eClassifiers xsi:type="ecore:EClass" name="JavaElement" eSuperTypes="#//ArtifactElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ElementIdentifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ElementProfile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//JavaAnnotation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaAnnotation" eSuperTypes="#//ArtifactElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AnnotationName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//JavaAnnotationParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaAnnotationParameter" eSuperTypes="#//ArtifactElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ParameterName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="value"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ParameterValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaDataType" eSuperTypes="#//JavaElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsPrimitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="JsonSchema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PackageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="java.lang"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaUserDefinedType" eSuperTypes="#//JavaDataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" lowerBound="1"
        upperBound="-1" eType="#//JavaMethod" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
        eType="#//JavaUserDefinedType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//JavaUserDefinedType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defines" upperBound="-1"
        eType="#//JavaUserDefinedType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//JavaDataField" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaClassType" eSuperTypes="#//JavaUserDefinedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implements" upperBound="-1"
        eType="#//JavaInterfaceType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaInterfaceType" eSuperTypes="#//JavaUserDefinedType"/>
  <eClassifiers xsi:type="ecore:EClass" name="JavaMethod" eSuperTypes="#//JavaElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RootCallingMethod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//JavaUserDefinedType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//JavaMethodParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returns" eType="#//JavaDataType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invokes" upperBound="-1"
        eType="#//JavaMethod" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//JavaDataField" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaDataField" eSuperTypes="#//JavaElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FieldValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="NOT_APPLICABLE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//JavaDataType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaMethodParameter" eSuperTypes="#//JavaDataField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ParameterOrder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
</ecore:EPackage>
